"""
setup.py — the platform-aware onboarding wizard.

THE PROBLEM IT SOLVES
    Signup handed you an API key and a page of Jenkins Groovy, whichever CI you
    actually used, and then never told you whether any of it worked. The snippet
    also hardcoded seven of the ten features, so someone who followed the
    instructions exactly got a score that barely depended on their build.

    Four steps, and the fourth is the one that matters:

      1. pick your platform          -> saved on the tenant record
      2. add the secrets             -> exact names, exact place to paste them
      3. paste the snippet           -> real extractor, prerequisites inline
      4. verify                      -> poll until a real build arrives

    Step 4 is what turns "I pasted some YAML" into "it works". Without it the
    user's first signal is silence, and silence is indistinguishable from a
    misconfiguration.

Every snippet is generated by app/integrations/<platform>.py, so this module
holds no platform knowledge and adding GitLab later touches one file.
"""
from __future__ import annotations

import os
import sys

from flask import Blueprint, jsonify, redirect, render_template, request, session

_app_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _app_dir)

import integrations                                            # noqa: E402
from dynamo_client import (set_ci_platform, set_onboarding_step,  # noqa: E402
                           validate_tenant)
from integrations import public_base_url                        # noqa: E402
from observability import get_logger                            # noqa: E402
from redirects import login_url                                 # noqa: E402

setup_bp = Blueprint("setup", __name__)
log = get_logger("routes.setup")


def _current():
    """(tenant_id, api_key, tenant) or (None, None, None)."""
    tenant_id = request.args.get("tenant_id") or session.get("tenant_id", "")
    api_key = request.args.get("api_key") or session.get("api_key", "")
    if not tenant_id or not api_key:
        return None, None, None
    tenant = validate_tenant(tenant_id, api_key)
    if not tenant:
        return None, None, None
    session["tenant_id"] = tenant_id
    session["api_key"] = api_key
    session.permanent = True
    return tenant_id, api_key, tenant


def _build_count(tenant):
    try:
        return int(tenant.get("build_count", 0) or 0)
    except (TypeError, ValueError):
        return 0


# ── the wizard ───────────────────────────────────────────────────────────────

#: The wizard, in order. `needs_platform` marks the steps that cannot render
#: without one, so a deep link to step 3 before choosing lands on step 1 rather
#: than on a blank page.
STEPS = (
    {"n": 1, "key": "platform", "label": "Platform", "needs_platform": False},
    {"n": 2, "key": "secrets",  "label": "Secrets",  "needs_platform": True},
    {"n": 3, "key": "pipeline", "label": "Pipeline", "needs_platform": True},
    {"n": 4, "key": "verify",   "label": "Verify",   "needs_platform": True},
)
LAST_STEP = STEPS[-1]["n"]


def _requested_step(raw, chosen, furthest):
    """
    Which step to show.

    Explicit ?step= wins so Back, browser-back and a bookmarked link all behave.
    Without one, resume where they left off — someone who closed the tab to go
    and paste a secret should come back to the step they were on, not the start.
    """
    try:
        step = int(raw)
    except (TypeError, ValueError):
        step = furthest or 1

    step = max(1, min(LAST_STEP, step))
    if step > 1 and not chosen:
        return 1                      # nothing downstream renders without one
    return step


@setup_bp.route("/setup", methods=["GET"])
def setup():
    tenant_id, api_key, tenant = _current()
    if not tenant:
        # Come back here after logging in, keeping the platform they were
        # looking at. Landing on /dashboard instead means the page they asked
        # for is simply gone, with no way back to it.
        return redirect(login_url(request.path,
                                  {"platform": request.args.get("platform")}))

    # ?platform= lets someone re-pick without losing what they already saved.
    chosen = (request.args.get("platform")
              or tenant.get("ci_platform", "") or "").strip().lower()
    if chosen and not integrations.is_valid(chosen):
        chosen = ""

    try:
        furthest = int(tenant.get("onboarding_step", 0) or 0)
    except (TypeError, ValueError):
        furthest = 0

    count = _build_count(tenant)
    connected = count > 0
    step = _requested_step(request.args.get("step"), chosen,
                           LAST_STEP if connected else furthest)

    base_url = public_base_url()
    details = (integrations.describe(chosen, tenant_id, api_key, base_url)
               if chosen else None)

    if step > furthest:
        set_onboarding_step(tenant_id, step)

    return render_template(
        "setup.html",
        tenant_id=tenant_id, api_key=api_key,
        platforms=integrations.summaries(),
        chosen=chosen, details=details,
        base_url=base_url,
        # A wizard that tells you to paste an API key into a pipeline over plain
        # HTTP has not earned the trust it is asking for. Shown on the step that
        # actually reveals the key, not as a banner over the whole flow — a red
        # block before you have done anything reads as "this is broken".
        insecure_url=base_url.startswith("http://"),
        build_count=count,
        connected=connected,
        steps=STEPS, step=step, last_step=LAST_STEP,
        furthest=max(furthest, step),
    )


@setup_bp.route("/setup/platform", methods=["POST"])
def choose_platform():
    tenant_id, api_key, tenant = _current()
    if not tenant:
        return jsonify({"error": "not authenticated"}), 401

    data = request.get_json(silent=True) or {}
    platform = (data.get("platform") or "").strip().lower()
    if not integrations.is_valid(platform):
        return jsonify({"error": f"unknown platform {platform!r}",
                        "expected": list(integrations.ORDER)}), 400

    set_ci_platform(tenant_id, platform)
    log.info("ci platform chosen",
             extra={"tenant_id": tenant_id, "ci_platform": platform})
    # Straight on to step 2 — choosing is the whole of step 1, so making someone
    # then press Next is a click that carries no information.
    return jsonify({"ok": True, "platform": platform,
                    "redirect": f"/setup?platform={platform}&step=2"}), 200


@setup_bp.route("/api/setup/status", methods=["GET"])
def status():
    """
    Polled by step 4. Reports whether a real build has arrived yet, and if so
    shows the actual score — "Connected, build #1 scored 34 SAFE" is a far better
    confirmation than a green tick, because it proves the whole path worked and
    not merely that a request was received.
    """
    tenant_id, api_key, tenant = _current()
    if not tenant:
        return jsonify({"error": "not authenticated"}), 401

    count = _build_count(tenant)
    payload = {
        "connected": count > 0,
        "build_count": count,
        "ci_platform": tenant.get("ci_platform", ""),
        "latest": None,
    }

    if count:
        try:
            from routes.dashboard import _load_builds

            builds = _load_builds(tenant_id, 5)
            if builds:
                latest = builds[-1]
                score = int(latest.get("predicted_score", 0) or 0)
                payload["latest"] = {
                    "build_id": latest.get("build_id", ""),
                    "score": score,
                    "verdict": ("SAFE" if score <= 40
                                else "WARNING" if score <= 70 else "BLOCKED"),
                    "job_name": latest.get("job_name", ""),
                    "branch_name": latest.get("branch_name", ""),
                    # How much of that score was actually measured. A "connected"
                    # banner over a score built entirely on medians would be
                    # technically true and practically misleading.
                    "imputed": latest.get("imputed", ""),
                }
        except Exception as exc:                                # pragma: no cover
            log.warning("setup status could not load builds",
                        extra={"tenant_id": tenant_id, "err": str(exc)})

    return jsonify(payload), 200
